#!/bin/bash

# This is a quick and dirty script there are no error checking

#### Check for paru ####
ISAUR=/sbin/paru
if [ -f "$ISAUR" ]; then 
    echo -e "paru was located, moving on.\n"   
else 
    echo "installing paru..."
    ./inst-paru
fi

sudo pacman -S pipewire pipewire-alsa pipewire-audio pipewire-jack pipewire-media-session blueman ttf-jetbrains-mono-nerd noto-fonts-emoji noto-fonts-cjk ttf-font-awesome polkit-gnome mpv imv ffmpeg neovim hyprland pipewire dunst wofi swaybg grim slurp kitty imagemagick pamixer brightnessctl waybar xdg-desktop-portal-hyprland gvfs ntfs-3g cliphist lxappearance xfce4-settings clang bluez bluez-utils pulseaudio-bluetooth gnome-disk-utility gvfs-mtp btop qbittorrent thunar tumbler unzip file-roller android-tools xdg-user-dirs ranger python-pillow fzf jq

paru -S swaylock-effects-git catppuccin-gtk-theme-mocha visual-studio-code-bin invidtui-bin

  echo -e "Copying config files...\n"
  cp -R .config/btop ~/.config/
  cp -R .config/dunst ~/.config/
  cp -R .config/hypr ~/.config/
  cp -R .config/kitty ~/.config/
  cp -R .config/mpv ~/.config/
  cp -R .config/neofetch ~/.config/
  cp -R .config/ranger ~/.config/
  cp -R .config/swaylock ~/.config/
  cp -R .config/Thunar ~/.config/
  cp -R .config/waybar ~/.config/
  cp -R .config/wofi ~/.config/
  cp -R .config/xfce4 ~/.config/

  chmod +x ~/.config/hypr/scripts/batterynotify.sh
  chmod +x ~/.config/hypr/scripts/idlet.sh
  chmod +x ~/.config/hypr/scripts/power.sh
  chmod +x ~/.config/hypr/scripts/lookup.sh

read -n1 -rep 'Would you like to install fish? (y,n)' ZIH
if [[ $ZIH == "Y" || $ZIH == "y" ]]; then
    sudo pacman -S fish
    cp -R .config/shell/fish ~/.config/

    echo -e "Setting fish as default..\n"
    chsh -s /usr/bin/fish   
fi

systemctl enable --now bluetooth 
systemctl enable --now NetworkManager

### Script is done ###
echo -e "Script completed.\n"

read -n1 -rep 'Would you like to start Hyprland now? (y,n)' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec Hyprland
else
    exit
fi
